-   id: sync-pre-commit-deps
    name: sync-pre-commit-deps
    description: Sync pre-commit hook dependencies based on other installed hooks
    entry: sync-pre-commit-deps
    language: python
    language_version: python3
    files: '^\.pre-commit-config.yaml$'
